"use client";
import { Suspense, useEffect, useMemo, useState } from "react";
import { useSearchParams } from "react-router-dom";
import { Apple, BookOpen, Leaf, Plus, RefreshCcw, Search, Sprout } from "lucide-react";
import { AppShell } from "@/components/layout/AppShell";
import { SectionCard } from "@/components/ui/cards";
import { Button, Input, Label, Select } from "@/components/ui/primitives";
import { ComplexSwitcher, GreenhouseSwitcher } from "@/components/layout/bits";
import { useToast } from "@/components/ui/toast";
import { complexService, greenhouseService } from "@/lib/services";
import { operationalPythonClient, hydrateOperationalState } from "@/lib/operational-state";
import { useDbVersion } from "@/lib/useDb";
import type { ResearchCycle, ResearchFruit, ResearchPlant, ResearchObservation } from "@/lib/types";
import { errorMessage } from "@/lib/errors";

export default function ResearchPage(){ return <Suspense fallback={null}><ResearchContent/></Suspense>; }
function ResearchContent(){
  const [params,setParams]=useSearchParams(); const toast=useToast(); useDbVersion();
  const complexes=complexService.list(); const complexId=params.get("complex") ?? ""; const complex=complexId ? complexes.find(c=>c.id===complexId) : undefined;
  const ghs=complex?greenhouseService.byComplex(complex.id):[]; const ghId=params.get("gh") ?? ""; const gh=ghId ? ghs.find(g=>g.id===ghId) : undefined;
  const view=(params.get("view") as "cycles"|"plants"|"fruits"|"observations"|"harvest")??"cycles";
  const [cycles,setCycles]=useState<ResearchCycle[]>([]),[plants,setPlants]=useState<ResearchPlant[]>([]),[fruits,setFruits]=useState<ResearchFruit[]>([]),[observations,setObservations]=useState<ResearchObservation[]>([]),[selectedCycleId,setSelectedCycleId]=useState(""),[analysis,setAnalysis]=useState<any>(null),[loading,setLoading]=useState(false),[busy,setBusy]=useState(false);
  const [plantTag,setPlantTag]=useState(""),[plantPosition,setPlantPosition]=useState(""),[plantStatus,setPlantStatus]=useState("ALIVE"),[mortalityReason,setMortalityReason]=useState("");
  const [fruitPlantId,setFruitPlantId]=useState(""),[fruitTag,setFruitTag]=useState(""),[fruitWeight,setFruitWeight]=useState(""),[fruitGrade,setFruitGrade]=useState("");
  const [obsPlantId,setObsPlantId]=useState(""),[obsHeight,setObsHeight]=useState(""),[obsLeaves,setObsLeaves]=useState(""),[obsFruitCount,setObsFruitCount]=useState(""),[obsNotes,setObsNotes]=useState("");
  const refresh=async()=>{ if(!complex||!gh)return; setLoading(true); try{const [c,p,f,o]=await Promise.all([operationalPythonClient.getResearchCycles(complex.id,{ghId:gh.id,limit:100}),operationalPythonClient.getResearchPlants(complex.id,{ghId:gh.id}),operationalPythonClient.getResearchFruits(complex.id,{ghId:gh.id}),operationalPythonClient.getResearchObservations(complex.id,{ghId:gh.id})]); setCycles(c.cycles);setPlants(p.plants);setFruits(f.fruits);setObservations(o.observations);const active=c.cycles.find(x=>x.status==="ACTIVE");setSelectedCycleId(prev=>prev||active?.cycleId||"");if(active?.cycleId)try{setAnalysis(await operationalPythonClient.getResearchAnalysis(complex.id,active.cycleId));}catch{setAnalysis(null);} }catch(e){toast(errorMessage(e),"error");}finally{setLoading(false);}};
  useEffect(()=>{void refresh();},[complex?.id,gh?.id]);
  const currentCycle=cycles.find(x=>x.cycleId===selectedCycleId)??cycles.find(x=>x.status==="ACTIVE")??null; const cyclePlants=useMemo(()=>plants.filter(x=>!currentCycle||x.cycleId===currentCycle.cycleId),[plants,currentCycle?.cycleId]); const cycleFruits=useMemo(()=>fruits.filter(x=>!currentCycle||x.cycleId===currentCycle.cycleId),[fruits,currentCycle?.cycleId]); const cycleObs=useMemo(()=>observations.filter(x=>!currentCycle||x.cycleId===currentCycle.cycleId),[observations,currentCycle?.cycleId]);
  if(!complex)return <AppShell complexId=""><div className="p-8 text-center text-sm text-slate-400">No Complex configured. Create a Complex first.</div></AppShell>;
  const setView=(v:string)=>{const q=new URLSearchParams(params.toString());q.set("view",v);setParams(q,{replace:true});};
  const save=async(kind:"plant"|"fruit"|"observation")=>{if(!currentCycle||!gh){toast("Select an active crop cycle first.","error");return;}setBusy(true);try{if(kind==="plant"){if(!plantTag.trim())throw Error("Plant tag is required.");await operationalPythonClient.saveResearchPlant(complex.id,{cycleId:currentCycle.cycleId,ghId:gh.id,plantTag:plantTag.trim(),position:plantPosition.trim()||null,status:plantStatus,mortalityReason:mortalityReason.trim()||null});setPlantTag("");setPlantPosition("");setMortalityReason("");}else if(kind==="fruit"){if(!fruitPlantId)throw Error("Plant is required.");await operationalPythonClient.saveResearchFruit(complex.id,{plantId:fruitPlantId,fruitTag:fruitTag.trim()||null,weightG:fruitWeight===""?null:Number(fruitWeight),grade:fruitGrade.trim()||null});setFruitTag("");setFruitWeight("");setFruitGrade("");}else{if(!obsPlantId||!obsHeight)throw Error("Plant and height are required.");await operationalPythonClient.saveResearchObservation(complex.id,{cycleId:currentCycle.cycleId,ghId:gh.id,plantId:obsPlantId,metric:"plant_check",heightCm:Number(obsHeight),leafCount:obsLeaves===""?null:Number(obsLeaves),fruitCount:obsFruitCount===""?null:Number(obsFruitCount),notes:obsNotes.trim()||null,source:"WEB"});setObsHeight("");setObsLeaves("");setObsFruitCount("");setObsNotes("");}await hydrateOperationalState();await refresh();toast("Research record saved.","success");}catch(e){toast(errorMessage(e),"error");}finally{setBusy(false);}};
  const tabs=["cycles","plants","fruits","observations","harvest"] as const;
  return <AppShell complexId={complex.id}><div className="mb-5 flex flex-wrap items-end justify-between gap-4"><div><div className="flex items-center gap-2"><BookOpen className="h-5 w-5 text-emerald-500"/><h1 className="text-xl font-bold text-slate-900">Research</h1></div><p className="mt-1 text-[13px] text-slate-500">Persistent crop cycles, plant/fruit identity, observations and traceability.</p></div><div className="flex flex-wrap gap-3"><ComplexSwitcher complexId={complex.id} complexes={complexes}/>{gh&&<GreenhouseSwitcher complexId={complex.id} greenhouses={ghs} ghId={gh.id}/>}</div></div>
    <div className="mb-4 flex flex-wrap gap-2">{tabs.map(t=><button key={t} onClick={()=>setView(t)} className={`rounded-lg px-3 py-2 text-xs font-semibold capitalize ${view===t?"bg-slate-900 text-white":"border border-slate-200 bg-white text-slate-500"}`}>{t}</button>)}<Button variant="secondary" size="sm" onClick={()=>void refresh()} disabled={loading}><RefreshCcw className="mr-1.5 h-3.5 w-3.5"/>Refresh</Button></div>
    {!gh?<div className="rounded-xl border border-dashed border-slate-200 p-8 text-center text-sm text-slate-400">No Greenhouse configured in this Complex.</div>:<>
    <SectionCard title="Crop cycle" icon={Sprout} iconTone="green"><div className="flex flex-wrap items-center gap-3"><Select value={selectedCycleId} onChange={e=>{setSelectedCycleId(e.target.value);operationalPythonClient.getResearchAnalysis(complex.id,e.target.value).then(setAnalysis).catch(()=>setAnalysis(null));}} options={cycles.length?cycles.map(c=>({value:c.cycleId,label:`${c.cycleId} · ${c.status}`})):[{value:"",label:"No cycle"}]} className="min-w-64"/>{currentCycle&&<div className="grid grid-cols-3 gap-2 text-center text-xs"><div className="rounded-lg bg-slate-50 px-3 py-2"><b className="text-lg">{currentCycle.hst??"—"}</b><div className="text-slate-400">HST</div></div><div className="rounded-lg bg-slate-50 px-3 py-2"><b className="text-lg">{currentCycle.hsp??"—"}</b><div className="text-slate-400">HSP</div></div><div className="rounded-lg bg-slate-50 px-3 py-2"><b className="text-lg">{currentCycle.plantCount}</b><div className="text-slate-400">Plants</div></div></div>}</div>{currentCycle&&<div className="mt-3 grid gap-3 md:grid-cols-4 text-xs"><div><div className="text-slate-400">Planting</div><b>{currentCycle.plantingDate??"—"}</b></div><div><div className="text-slate-400">Pollination</div><b>{currentCycle.pollinationDate??"—"}</b></div><div><div className="text-slate-400">Harvest</div><b>{currentCycle.actualHarvestDate??"—"}</b></div><div><div className="text-slate-400">Yield</div><b>{currentCycle.yieldKg??"—"} kg</b></div></div>}</SectionCard>
    {view==="plants"&&<SectionCard title="Plant registry" icon={Leaf} iconTone="green"><div className="grid gap-2 md:grid-cols-5"><div><Label>Plant tag</Label><Input value={plantTag} onChange={e=>setPlantTag(e.target.value)} placeholder="P-001"/></div><div><Label>Position</Label><Input value={plantPosition} onChange={e=>setPlantPosition(e.target.value)} placeholder="Row 1 / Slot 1"/></div><div><Label>Status</Label><Select value={plantStatus} onChange={e=>setPlantStatus(e.target.value)} options={[{value:"ALIVE",label:"Alive"},{value:"DEAD",label:"Dead"},{value:"REMOVED",label:"Removed"}]}/></div><div><Label>Mortality reason</Label><Input value={mortalityReason} onChange={e=>setMortalityReason(e.target.value)} placeholder="Optional"/></div><div className="flex items-end"><Button onClick={()=>void save("plant")} disabled={busy}><Plus className="mr-1.5 h-4 w-4"/>Add plant</Button></div></div><div className="mt-4 space-y-2">{cyclePlants.map(p=><div key={p.plantId} className="grid grid-cols-4 rounded-lg border border-slate-200 px-3 py-2 text-xs"><b>{p.plantTag}</b><span>{p.position??"—"}</span><span>{p.status}</span><span>{p.mortalityReason??"—"}</span></div>)}{!cyclePlants.length&&<div className="p-6 text-center text-sm text-slate-400">No plants recorded yet.</div>}</div></SectionCard>}
    {view==="fruits"&&<SectionCard title="Fruit registry" icon={Apple} iconTone="slate"><div className="grid gap-2 md:grid-cols-5"><div><Label>Plant</Label><Select value={fruitPlantId} onChange={e=>setFruitPlantId(e.target.value)} options={[{value:"",label:"Select plant"},...cyclePlants.map(p=>({value:p.plantId,label:p.plantTag}))]}/></div><div><Label>Fruit tag</Label><Input value={fruitTag} onChange={e=>setFruitTag(e.target.value)} placeholder="F-001"/></div><div><Label>Weight (g)</Label><Input type="number" min="0" value={fruitWeight} onChange={e=>setFruitWeight(e.target.value)} placeholder="Measured"/></div><div><Label>Grade</Label><Input value={fruitGrade} onChange={e=>setFruitGrade(e.target.value)} placeholder="Measured grade"/></div><div className="flex items-end"><Button onClick={()=>void save("fruit")} disabled={busy}><Plus className="mr-1.5 h-4 w-4"/>Add fruit</Button></div></div><div className="mt-4 space-y-2">{cycleFruits.map(f=><div key={f.fruitId} className="grid grid-cols-4 rounded-lg border border-slate-200 px-3 py-2 text-xs"><b>{f.fruitTag??f.fruitId}</b><span>{cyclePlants.find(p=>p.plantId===f.plantId)?.plantTag??f.plantId}</span><span>{f.weightG??"—"} g</span><span>{f.grade??"—"}</span></div>)}{!cycleFruits.length&&<div className="p-6 text-center text-sm text-slate-400">No fruits recorded yet.</div>}</div></SectionCard>}
    {view==="observations"&&<SectionCard title="Plant observations" icon={Search} iconTone="slate"><div className="grid gap-2 md:grid-cols-6"><div><Label>Plant</Label><Select value={obsPlantId} onChange={e=>setObsPlantId(e.target.value)} options={[{value:"",label:"Select plant"},...cyclePlants.map(p=>({value:p.plantId,label:p.plantTag}))]}/></div><div><Label>Height (cm)</Label><Input type="number" min="0" value={obsHeight} onChange={e=>setObsHeight(e.target.value)} placeholder="Measured"/></div><div><Label>Leaves</Label><Input type="number" min="0" value={obsLeaves} onChange={e=>setObsLeaves(e.target.value)} placeholder="Optional"/></div><div><Label>Fruits</Label><Input type="number" min="0" value={obsFruitCount} onChange={e=>setObsFruitCount(e.target.value)} placeholder="Optional"/></div><div><Label>Notes</Label><Input value={obsNotes} onChange={e=>setObsNotes(e.target.value)} placeholder="Optional"/></div><div className="flex items-end"><Button onClick={()=>void save("observation")} disabled={busy}><Plus className="mr-1.5 h-4 w-4"/>Record</Button></div></div><div className="mt-4 space-y-2">{cycleObs.slice(0,100).map(o=><div key={o.observationId} className="rounded-lg border border-slate-200 px-3 py-2 text-xs"><div className="flex justify-between"><b>{cyclePlants.find(p=>p.plantId===o.plantId)?.plantTag??o.plantId??"—"}</b><span className="text-slate-400">{new Date(o.observedAt).toLocaleString("id-ID")}</span></div><div className="mt-1 text-slate-500">{o.heightCm??"—"} cm · {o.leafCount??"—"} leaves · {o.fruitCount??"—"} fruits{o.notes?` · ${o.notes}`:""}</div></div>)}{!cycleObs.length&&<div className="p-6 text-center text-sm text-slate-400">No observations recorded yet.</div>}</div></SectionCard>}
    {(view==="cycles"||view==="harvest")&&<SectionCard title={view==="harvest"?"Harvest & analysis":"Cycle history"} icon={view==="harvest"?Apple:Sprout} iconTone={view==="harvest"?"slate":"green"}><div className="space-y-2">{cycles.map(c=><button key={c.cycleId} onClick={()=>{setSelectedCycleId(c.cycleId);operationalPythonClient.getResearchAnalysis(complex.id,c.cycleId).then(setAnalysis).catch(()=>setAnalysis(null));}} className={`w-full rounded-lg border px-3 py-3 text-left ${c.cycleId===selectedCycleId?"border-emerald-300 bg-emerald-50/40":"border-slate-200"}`}><div className="flex justify-between"><b>{c.cycleId}</b><span className="text-xs text-slate-400">{c.status}</span></div><div className="mt-1 text-xs text-slate-500">{c.plantingDate??"—"} → {c.actualHarvestDate??"ongoing"} · HST {c.hst??"—"} · Yield {c.yieldKg??"—"} kg</div></button>)}{!cycles.length&&<div className="p-6 text-center text-sm text-slate-400">No historical cycles yet.</div>}</div>{analysis&&<div className="mt-4 grid gap-2 md:grid-cols-6 text-xs">{Object.entries(analysis.counts??{}).map(([k,v])=><div key={k} className="rounded-lg bg-slate-50 px-3 py-2"><div className="text-slate-400">{k}</div><div className="text-lg font-bold text-slate-900">{String(v)}</div></div>)}</div>}</SectionCard>}
    </>}
  </AppShell>
}
