idf_component_register(
    SRCS
        "main.c"
        "hal/actuator_hal.c"
        "hal/sensor_hal.c"
        "hal/button_hal.c"
        "hal/hardware_registry.c"
        "hal/sdcard_hal.c"
        "hal/rtc_ds3231.c"
        "hal/tft_hal.c"
        "network/network_mgr.c"
        "storage/storage_mgr.c"
        "services/command_mgr.c"
        "services/safety_monitor.c"
        "services/scheduler.c"
        "services/crop_cycle_mgr.c"
        "services/telemetry_mgr.c"
        "services/event_mgr.c"
        "services/fertigation_mgr.c"
        "services/manual_actuator_mgr.c"
        "services/transfer_mgr.c"
        "services/calibration_mgr.c"
        "services/panel_button_mgr.c"
        "http/http_server.c"
        "http/api_device_handlers.c"
        "http/api_config_handlers.c"
        "http/api_command_handlers.c"
        "http/api_cropcycle_handlers.c"
        "http/api_telemetry_handlers.c"
        "http/api_calibration_handlers.c"
        "http/api_schedule_handlers.c"
    INCLUDE_DIRS
        "."
        "config"
        "hal"
        "services"
        "http"
        "storage"
        "network"
    REQUIRES
        esp_http_server
        mdns
        nvs_flash
        esp_wifi
        esp_netif
        json
        driver
        spiffs
        fatfs
        vfs
        esp_timer
        esp_event
        spi_flash
)
