"use client";

import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, Calendar, Clock, Leaf, RotateCcw, Save, Settings2, Sprout, Trash2, Wheat, Plus, Wrench, X } from "lucide-react";
import { Modal, ConfirmDialog } from "@/components/ui/overlay";
import { MaintenanceScheduleModal } from "./MaintenanceScheduleModal";
import { Button, Input, Label } from "@/components/ui/primitives";
import type { CropCycle, Greenhouse } from "@/lib/types";
import { calculateDaysBetween, getSystemDate, toIsoDateString, validateTanggalPolinasi, validateTanggalTanam } from "@/lib/cropCycleProcessor";

type TimelinePoint = { id:string; name:string; startHst:string; endHst:string; note:string };
type MaintenancePoint = { id:string; name:string; hst:string; category:string; note:string };
type View = "home" | "tanam" | "polinasi" | "tanaman" | "timeline" | "maintenance" | "opsi";
const key=(id:string)=>`greenhouse-crop-timeline:${id}`;
const defaults=():TimelinePoint[]=>[
 {id:"seed",name:"Semai",startHst:"0",endHst:"10",note:""},{id:"vegetative",name:"Vegetatif",startHst:"11",endHst:"25",note:""},{id:"flowering",name:"Berbunga",startHst:"26",endHst:"45",note:""},{id:"fruiting",name:"Pembuahan",startHst:"46",endHst:"65",note:""},{id:"ripening",name:"Pematangan",startHst:"66",endHst:"85",note:""},{id:"harvest",name:"Panen",startHst:"86",endHst:"90",note:""}
];
const defaultMaintenancePoints=():MaintenancePoint[]=>[];

export interface CycleManageModalProps {
 gh:Greenhouse; cycle?:CropCycle; open:boolean; onClose:()=>void; onUpdateTanggalTanam:(date:string)=>Promise<void>; onUpdateTanggalPolinasi:(date:string)=>Promise<void>; onUpdateMetadata?:(updates:{variety?:string;plantCount?:number;notes?:string})=>Promise<void>; onDeleteTanggalPolinasi:()=>Promise<void>; onResetCycle?:()=>Promise<void>;
}

export function CycleManageModal({gh,cycle,open,onClose,onUpdateTanggalTanam,onUpdateTanggalPolinasi,onUpdateMetadata,onDeleteTanggalPolinasi,onResetCycle}:CycleManageModalProps){
 const today=useMemo(()=>toIsoDateString(getSystemDate()),[]);
 const [view,setView]=useState<View>("home"); const [busy,setBusy]=useState(false); const [error,setError]=useState<string|null>(null);
 const [tanamDate,setTanamDate]=useState(""); const [polDate,setPolDate]=useState(""); const [variety,setVariety]=useState(""); const [plants,setPlants]=useState(120); const [notes,setNotes]=useState("");
 const [target,setTarget]=useState("90"); const [points,setPoints]=useState<TimelinePoint[]>(defaults()); const [maintenance,setMaintenance]=useState<MaintenancePoint[]>(defaultMaintenancePoints()); const [confirmDelete,setConfirmDelete]=useState(false); const [confirmReset,setConfirmReset]=useState(false); const [maintenanceModalOpen,setMaintenanceModalOpen]=useState(false);
 useEffect(()=>{if(!open)return;setView("home");setError(null);setTanamDate(cycle?.tanggalTanam||today);setPolDate(cycle?.tanggalPolinasi||today);setVariety(cycle?.variety||gh.crop);setPlants(gh.plants?.total||120);setNotes("");try{const raw=localStorage.getItem(key(gh.id));if(raw){const saved=JSON.parse(raw);setTarget(String(saved.targetHarvestHst??90));setPoints(Array.isArray(saved.points)&&saved.points.length?saved.points:defaults());setMaintenance(Array.isArray(saved.maintenance)?saved.maintenance.map((m:any,index:number)=>({id:String(m.id??`maintenance-${index}`),name:String(m.name??""),hst:String(m.hst??""),category:String(m.category??"Lainnya"),note:String(m.note??"")})):defaultMaintenancePoints())}else{setTarget("90");setPoints(defaults());setMaintenance(defaultMaintenancePoints())}}catch{setTarget("90");setPoints(defaults());setMaintenance(defaultMaintenancePoints())}},[open,cycle,today,gh.id,gh.crop,gh.plants?.total]);
 const hst=gh.telemetry.hstDays; const nextHst=calculateDaysBetween(tanamDate); const hsp=gh.telemetry.hspDays; const nextHsp=calculateDaysBetween(polDate);
 const setPage=(v:View)=>{setView(v);setError(null)};
 const run=async(task:()=>Promise<void>,message:string)=>{setBusy(true);setError(null);try{await task();setView("home")}catch(e:unknown){setError(e instanceof Error?e.message:message)}finally{setBusy(false)}};
 const saveTimeline=()=>{const t=Number(target);if(!Number.isFinite(t)||t<=0)return setError("Rencana Panen harus berupa HST lebih besar dari 0.");if(points.some(p=>!p.name.trim()||p.startHst===""||p.endHst===""||Number(p.startHst)>Number(p.endHst)))return setError("Lengkapi semua fase timeline.");const sorted=[...points].sort((a,b)=>Number(a.startHst)-Number(b.startHst));for(let i=1;i<sorted.length;i++)if(Number(sorted[i].startHst)<=Number(sorted[i-1].endHst))return setError("Rentang fase timeline tidak boleh bertumpuk.");if(sorted.some(p=>Number(p.endHst)>t))return setError("Fase tidak boleh melewati Rencana Panen.");if(maintenance.some(m=>!m.name.trim()||m.hst===""||!Number.isFinite(Number(m.hst))||Number(m.hst)<0||Number(m.hst)>t))return setError("Jadwal perawatan harus memiliki HST 0 sampai Rencana Panen.");const config={targetHarvestHst:t,points:sorted.map(p=>({...p,name:p.name.trim(),note:p.note.trim()})),maintenance:[...maintenance].sort((a,b)=>Number(a.hst)-Number(b.hst)).map(m=>({...m,name:m.name.trim(),category:m.category.trim()||"Lainnya",note:m.note.trim()}))};localStorage.setItem(key(gh.id),JSON.stringify(config));window.dispatchEvent(new CustomEvent("crop-timeline-config-updated",{detail:{ghId:gh.id,config}}));setView("home")};
 const homeCards:[View,string,string,React.ReactNode][]=[ ["tanam","Tanggal Tanam","Koreksi awal siklus dan lihat dampak HST",<Calendar className="h-5 w-5"/>],["polinasi","Tanggal Polinasi",cycle?.tanggalPolinasi?"Ubah atau hapus pencatatan polinasi":"Belum ada tanggal polinasi",<Clock className="h-5 w-5"/>],["tanaman","Data Tanaman",`${variety||gh.crop} • ${plants} tanaman`,<Leaf className="h-5 w-5"/>],["timeline","Timeline Masa Tanam","Atur fase HST yang tampil di dashboard",<Wheat className="h-5 w-5"/>],["opsi","Zona Perawatan","Reset siklus atau tindakan berisiko",<Settings2 className="h-5 w-5"/>],["maintenance","Rencana Jadwal Perawatan",maintenance.length===0?"Atur pemupukan, pemangkasan, pengendalian hama, inspeksi, dan tindakan lain":"Kelola jadwal perawatan yang sudah direncanakan",<Wrench className="h-5 w-5"/>] ];
 const header=view==="home"?<div><div className="text-base font-bold text-slate-900">Kelola Siklus</div><div className="text-xs text-slate-500">Command center • {gh.code} • {gh.crop}</div></div>:<button type="button" className="flex items-center gap-2 text-left" onClick={()=>setPage("home")}><span className="flex h-8 w-8 items-center justify-center rounded-lg bg-slate-100 text-slate-700"><ArrowLeft className="h-4 w-4"/></span><div><div className="text-base font-bold text-slate-900">{({tanam:"Tanggal Tanam",polinasi:"Tanggal Polinasi",tanaman:"Data Tanaman",timeline:"Timeline Masa Tanam",maintenance:"Rencana Jadwal Perawatan",opsi:"Zona Perawatan"} as Record<string,string>)[view]}</div><div className="text-xs text-slate-500">Kembali ke command center</div></div></button>;
 return <><Modal open={open} onClose={onClose} title={<div className="flex items-center gap-2.5"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-emerald-100 text-emerald-700"><Sprout className="h-5 w-5"/></span>{header}</div>} footer={view==="home"?<div className="flex justify-end"><Button variant="ghost" onClick={onClose}>Tutup</Button></div>:<div className="flex justify-between gap-2"><Button variant="ghost" onClick={()=>setPage("home")} disabled={busy}>Kembali</Button>{view==="tanam"&&<Button onClick={()=>{const v=validateTanggalTanam(tanamDate);if(!v.valid)return setError(v.error||"Tanggal tidak valid");if(cycle?.tanggalPolinasi&&!validateTanggalPolinasi(cycle.tanggalPolinasi,tanamDate).valid)return setError("Tanggal tanam baru tidak boleh melebihi tanggal polinasi.");run(()=>onUpdateTanggalTanam(tanamDate),"Gagal mengubah tanggal tanam")}} disabled={busy||tanamDate===cycle?.tanggalTanam} className="bg-emerald-600 text-white">{busy?"Menyimpan...":"Simpan Tanggal Tanam"}</Button>}{view==="polinasi"&&cycle?.tanggalPolinasi&&<Button onClick={()=>{const v=validateTanggalPolinasi(polDate,cycle.tanggalTanam);if(!v.valid)return setError(v.error||"Tanggal tidak valid");run(()=>onUpdateTanggalPolinasi(polDate),"Gagal mengubah tanggal polinasi");}} disabled={busy||polDate===cycle.tanggalPolinasi} className="bg-violet-600 text-white">{busy?"Menyimpan...":"Simpan Polinasi"}</Button>}{view==="tanaman"&&<Button onClick={()=>onUpdateMetadata&&run(()=>onUpdateMetadata({variety:variety.trim(),plantCount:Number(plants)||gh.plants.total,notes:notes.trim()||undefined}),"Gagal memperbarui data tanaman")} disabled={busy||!onUpdateMetadata} className="bg-emerald-600 text-white"><Save className="mr-1.5 h-4 w-4"/>{busy?"Menyimpan...":"Simpan Data"}</Button>}{view==="timeline"&&<Button onClick={saveTimeline} disabled={busy} className="bg-emerald-600 text-white"><Save className="mr-1.5 h-4 w-4"/>Simpan Timeline</Button>}</div>}>
 <div className="max-h-[62dvh] overflow-y-auto">
 {view==="home"&&<div className="space-y-3"><div className="grid grid-cols-2 gap-3 rounded-2xl bg-slate-900 p-4 text-white"><div><div className="text-[10px] uppercase tracking-wider text-white/50">HST</div><div className="mt-1 text-2xl font-bold">{hst}<span className="ml-1 text-xs font-medium">hari</span></div></div><div><div className="text-[10px] uppercase tracking-wider text-white/50">HSP</div><div className="mt-1 text-2xl font-bold">{hsp==null?"–":hsp}<span className="ml-1 text-xs font-medium">hari</span></div></div></div><div className="grid gap-2 sm:grid-cols-2">{homeCards.map(([id,title,desc,icon])=><button key={id} type="button" onClick={()=>setPage(id)} className="group flex items-start gap-3 rounded-2xl border border-slate-200 bg-white p-4 text-left transition hover:border-emerald-300 hover:bg-emerald-50/40"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-slate-100 text-slate-700 group-hover:bg-emerald-100 group-hover:text-emerald-700">{icon}</span><span className="min-w-0"><span className="block text-sm font-bold text-slate-900">{title}</span><span className="mt-1 block text-xs leading-5 text-slate-500">{desc}</span></span></button>)}</div><div className="rounded-xl bg-slate-50 p-3 text-xs text-slate-600">Pilih satu tindakan. Setiap perubahan disimpan melalui service yang sama seperti sebelumnya; modal ini hanya mengatur input dan presentasi.</div></div>}
 {view==="tanam"&&<div className="space-y-4"><div><Label htmlFor="manage-tanam">Tanggal Tanam</Label><Input id="manage-tanam" type="date" max={today} value={tanamDate} onChange={e=>{setTanamDate(e.target.value);setError(null)}} className="mt-1.5 w-full"/></div><div className="grid grid-cols-2 gap-3"><div className="rounded-xl bg-slate-50 p-3"><div className="text-[11px] text-slate-500">HST saat ini</div><div className="mt-1 text-xl font-bold">{hst} hari</div></div><div className="rounded-xl bg-emerald-50 p-3"><div className="text-[11px] text-emerald-600">Setelah diubah</div><div className="mt-1 text-xl font-bold text-emerald-700">{nextHst} hari</div></div></div></div>}
 {view==="polinasi"&&<div className="space-y-4">{cycle?.tanggalPolinasi?<><div><Label htmlFor="manage-pol">Tanggal Polinasi</Label><Input id="manage-pol" type="date" min={cycle.tanggalTanam||undefined} max={today} value={polDate} onChange={e=>{setPolDate(e.target.value);setError(null)}} className="mt-1.5 w-full"/></div><div className="rounded-xl bg-violet-50 p-4"><div className="text-xs text-violet-600">HSP setelah perubahan</div><div className="mt-1 text-2xl font-bold text-violet-700">{nextHsp} hari</div></div><Button variant="danger" onClick={()=>setConfirmDelete(true)} disabled={busy}><Trash2 className="mr-1.5 h-4 w-4"/>Hapus Tanggal Polinasi</Button></>:<div className="rounded-2xl border border-dashed border-slate-300 p-8 text-center text-sm text-slate-500">Belum ada tanggal polinasi. Catat polinasi dari kartu siklus di dashboard.</div>}</div>}
 {view==="tanaman"&&<div className="space-y-4"><div><Label htmlFor="manage-variety">Varietas</Label><Input id="manage-variety" value={variety} onChange={e=>setVariety(e.target.value)} className="mt-1.5 w-full"/></div><div><Label htmlFor="manage-plants">Jumlah Tanaman</Label><Input id="manage-plants" type="number" min={1} value={plants} onChange={e=>setPlants(Number(e.target.value))} className="mt-1.5 w-full"/></div><div><Label htmlFor="manage-notes">Catatan</Label><textarea id="manage-notes" value={notes} onChange={e=>setNotes(e.target.value)} className="mt-1.5 min-h-20 w-full rounded-xl border border-slate-200 p-3 text-sm"/></div></div>}
 {view==="timeline"&&<div className="space-y-5">
 <div>
  <Label htmlFor="target-hst">Rencana Panen (HST)</Label>
  <Input id="target-hst" type="number" min={1} value={target} onChange={e=>setTarget(e.target.value)} className="mt-1.5 w-full"/>
 </div>
 <section className="space-y-3">
  <div className="flex items-center justify-between gap-3">
   <div><div className="text-sm font-bold text-slate-900">Fase Masa Tanam</div><div className="text-xs text-slate-500">Rentang HST yang tampil sebagai fase utama di dashboard.</div></div>
   <Button variant="secondary" onClick={()=>setPoints(a=>[...a,{id:`custom-${Date.now()}`,name:"",startHst:"",endHst:"",note:""}])}><Plus className="mr-1.5 h-4 w-4"/>Tambah Fase</Button>
  </div>
  <div className="space-y-2">{points.map(p=><div key={p.id} className="rounded-xl border border-slate-200 p-3"><div className="flex items-center gap-2"><Input value={p.name} onChange={e=>setPoints(a=>a.map(x=>x.id===p.id?{...x,name:e.target.value}:x))} placeholder="Nama fase"/><button type="button" className="text-xs text-red-500" onClick={()=>setPoints(a=>a.filter(x=>x.id!==p.id))}>Hapus</button></div><div className="mt-2 grid grid-cols-2 gap-2"><Input type="number" value={p.startHst} onChange={e=>setPoints(a=>a.map(x=>x.id===p.id?{...x,startHst:e.target.value}:x))} placeholder="Mulai HST"/><Input type="number" value={p.endHst} onChange={e=>setPoints(a=>a.map(x=>x.id===p.id?{...x,endHst:e.target.value}:x))} placeholder="Selesai HST"/></div><div className="mt-2"><Input value={p.note} onChange={e=>setPoints(a=>a.map(x=>x.id===p.id?{...x,note:e.target.value}:x))} placeholder="Catatan fase (opsional)"/></div></div>)}</div>
 </section>

 </div>}
 {view==="maintenance"&&<div className="space-y-4"><div className="rounded-2xl border border-amber-200 bg-amber-50 p-4"><div className="flex items-start gap-3"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-amber-100 text-amber-700"><Wrench className="h-5 w-5"/></span><div><div className="text-sm font-bold text-amber-950">Rencana Jadwal Perawatan</div><div className="mt-1 text-xs leading-5 text-amber-800">Rencanakan tindakan perawatan berdasarkan HST. Jadwal yang disimpan akan ditampilkan sebagai point pada Timeline Masa Tanam.</div></div></div></div><div className="rounded-2xl border border-slate-200 bg-white p-4"><div className="flex items-center justify-between gap-3"><div><div className="text-sm font-bold text-slate-900">Jadwal saat ini</div><div className="mt-1 text-xs text-slate-500">{maintenance.length===0?"Belum ada jadwal perawatan.":`${maintenance.length} jadwal tersimpan.`}</div></div><Button variant="secondary" onClick={()=>setMaintenanceModalOpen(true)}><Wrench className="mr-1.5 h-4 w-4"/>Kelola Jadwal</Button></div>{maintenance.length>0&&<div className="mt-4 space-y-2">{[...maintenance].sort((a,b)=>Number(a.hst)-Number(b.hst)).map(m=><div key={m.id} className="flex items-center justify-between rounded-xl border border-slate-200 px-3 py-2.5"><div className="min-w-0"><div className="truncate text-xs font-bold text-slate-800">{m.name}</div><div className="mt-0.5 truncate text-[11px] text-slate-500">{m.category}{m.note?` • ${m.note}`:""}</div></div><div className="ml-3 shrink-0 rounded-lg bg-amber-100 px-2 py-1 text-[11px] font-bold text-amber-700">HST {m.hst}</div></div>)}</div>}</div></div>}
 {view==="opsi"&&<div className="space-y-3"><div className="rounded-2xl border border-amber-200 bg-amber-50 p-4"><div className="flex gap-3"><RotateCcw className="h-5 w-5 text-amber-600"/><div><div className="text-sm font-bold text-amber-900">Reset Siklus</div><div className="mt-1 text-xs leading-5 text-amber-800">Kembalikan status siklus dan gunakan alur mulai tanam dari awal.</div><Button variant="danger" className="mt-3" onClick={()=>setConfirmReset(true)} disabled={!onResetCycle||busy}>Reset Siklus</Button></div></div></div></div>}
 {error&&<div className="mt-4 rounded-xl border border-red-200 bg-red-50 p-3 text-xs text-red-700">{error}</div>}
 </div></Modal><MaintenanceScheduleModal open={maintenanceModalOpen} targetHarvestHst={Number(target)||90} value={maintenance} onClose={()=>setMaintenanceModalOpen(false)} onSave={next=>setMaintenance(next)} /><ConfirmDialog open={confirmDelete} title="Hapus Tanggal Polinasi?" message="HSP akan di-reset. Tindakan ini mengubah data siklus aktif." confirmLabel="Hapus" danger onClose={()=>setConfirmDelete(false)} onConfirm={()=>run(async()=>{await onDeleteTanggalPolinasi();setConfirmDelete(false);},"Gagal menghapus tanggal polinasi")} /><ConfirmDialog open={confirmReset} title="Reset Siklus?" message="Siklus aktif akan dikembalikan ke status awal." confirmLabel="Reset Siklus" danger onClose={()=>setConfirmReset(false)} onConfirm={()=>run(async()=>{if(onResetCycle)await onResetCycle();setConfirmReset(false)},"Gagal mereset siklus")} /></>;
}
