"use client";
import { useEffect, useMemo, useState } from "react";
import type { FormEvent } from "react";
import { Flower2 } from "lucide-react";
import { Modal } from "@/components/ui/overlay";
import { Button, Input, Label } from "@/components/ui/primitives";
import type { CropCycle, Greenhouse } from "@/lib/types";
import { calculateDaysBetween, formatIndoDate, getSystemDate, toIsoDateString, validateTanggalPolinasi } from "@/lib/cropCycleProcessor";
interface Props { gh: Greenhouse; cycle?: CropCycle; polinasiOpen: boolean; onClosePolinasi:()=>void; onRecordPolinasi:(date:string, options?:{pollinationMethod?:"natural"|"bee"|"manual";notes?:string})=>Promise<void>; }
export function PollinationModal({gh,cycle,polinasiOpen,onClosePolinasi,onRecordPolinasi}:Props){
 const today=useMemo(()=>toIsoDateString(getSystemDate()),[]),[date,setDate]=useState(today),[method,setMethod]=useState<"natural"|"bee"|"manual">("natural"),[notes,setNotes]=useState(""),[saving,setSaving]=useState(false),[error,setError]=useState<string|null>(null);
 useEffect(()=>{if(polinasiOpen){setDate(cycle?.tanggalPolinasi||today);setMethod("natural");setNotes("");setError(null)}},[polinasiOpen,cycle?.tanggalPolinasi,today]);
 const validation=validateTanggalPolinasi(date,cycle?.tanggalTanam), hsp=validation.valid?calculateDaysBetween(date):0;
 const submit=async(e:FormEvent)=>{e.preventDefault();if(!validation.valid)return setError(validation.error||"Tanggal polinasi tidak valid");setSaving(true);setError(null);try{await onRecordPolinasi(date,{pollinationMethod:method,notes:notes.trim()||undefined});onClosePolinasi()}catch(err:unknown){setError(err instanceof Error?err.message:"Gagal mencatat polinasi")}finally{setSaving(false)}};
 return <Modal open={polinasiOpen} onClose={onClosePolinasi} title={<div className="flex items-center gap-2.5"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-violet-100 text-violet-700"><Flower2 className="h-5 w-5"/></span><div><div className="text-base font-bold text-slate-900">Catat Polinasi</div><div className="text-xs text-slate-500">{gh.code} • {gh.crop}</div></div></div>} footer={<div className="flex justify-end gap-2"><Button variant="ghost" onClick={onClosePolinasi} disabled={saving}>Batal</Button><Button onClick={submit} disabled={saving||!validation.valid} className="bg-violet-600 text-white hover:bg-violet-700">{saving?"Menyimpan...":"Simpan Polinasi"}</Button></div>}>
 <form onSubmit={submit} className="space-y-4"><div><Label htmlFor="pollination-date">Tanggal Polinasi</Label><Input id="pollination-date" type="date" min={cycle?.tanggalTanam||undefined} max={today} value={date} onChange={e=>{setDate(e.target.value);setError(null)}} className="mt-1.5 w-full"/></div><div className="grid grid-cols-3 gap-2">{([['natural','Natural'],['bee','Lebah'],['manual','Manual']] as const).map(([value,label])=><button type="button" key={value} onClick={()=>setMethod(value)} className={`rounded-xl border p-3 text-xs font-semibold ${method===value?'border-violet-500 bg-violet-50 text-violet-700':'border-slate-200 bg-white text-slate-600'}`}>{label}</button>)}</div><div className="rounded-xl bg-violet-50 p-4"><div className="text-[11px] uppercase tracking-wider text-violet-600">Preview HSP</div><div className="mt-1 flex items-baseline gap-2"><span className="text-3xl font-bold text-violet-700">{hsp}</span><span className="text-xs text-violet-600">hari setelah polinasi</span></div><div className="mt-1 text-[11px] text-violet-500">{validation.valid?formatIndoDate(date):"Tanggal belum valid"}</div></div><div><Label htmlFor="pollination-notes">Catatan</Label><textarea id="pollination-notes" value={notes} onChange={e=>setNotes(e.target.value)} className="mt-1.5 min-h-20 w-full rounded-xl border border-slate-200 p-3 text-sm"/></div>{error&&<div className="rounded-xl border border-red-200 bg-red-50 p-3 text-xs text-red-700">{error}</div>}</form>
 </Modal>;
}
